package org.talend.designer.codegen.translators.internet.ftp;

import org.talend.core.model.process.INode;
import org.talend.core.model.metadata.IMetadataTable;
import org.talend.core.model.process.ElementParameterParser;
import org.talend.designer.codegen.config.CodeGeneratorArgument;
import java.util.List;
import java.util.Map;

public class TFTPDeleteMainJava
{
  protected static String nl;
  public static synchronized TFTPDeleteMainJava create(String lineSeparator)
  {
    nl = lineSeparator;
    TFTPDeleteMainJava result = new TFTPDeleteMainJava();
    nl = null;
    return result;
  }

  public final String NL = nl == null ? (System.getProperties().getProperty("line.separator")) : nl;
  protected final String TEXT_1 = "";
  protected final String TEXT_2 = "\t" + NL + "String root";
  protected final String TEXT_3 = " = ftp";
  protected final String TEXT_4 = ".pwd();" + NL + "for (java.util.Map<String, String> map";
  protected final String TEXT_5 = " : list";
  protected final String TEXT_6 = ") " + NL + "{" + NL + "   java.util.Set<String> keySet";
  protected final String TEXT_7 = " = map";
  protected final String TEXT_8 = ".keySet(); " + NL + "   for (String key";
  protected final String TEXT_9 = " : keySet";
  protected final String TEXT_10 = ")" + NL + "   {     " + NL + "    \tString filemask";
  protected final String TEXT_11 = " = key";
  protected final String TEXT_12 = "; " + NL + "    \tString dir";
  protected final String TEXT_13 = " = null;" + NL + "    \tString mask";
  protected final String TEXT_14 = " = filemask";
  protected final String TEXT_15 = ".replaceAll(\"\\\\\\\\\", \"/\") ;" + NL + "    \tint i";
  protected final String TEXT_16 = " = mask";
  protected final String TEXT_17 = ".lastIndexOf('/');" + NL + "\t\tif (i";
  protected final String TEXT_18 = "!=-1)" + NL + "\t\t{" + NL + "\t\t\tdir";
  protected final String TEXT_19 = " = mask";
  protected final String TEXT_20 = ".substring(0, i";
  protected final String TEXT_21 = "); " + NL + "\t\t\tmask";
  protected final String TEXT_22 = " = mask";
  protected final String TEXT_23 = ".substring(i";
  protected final String TEXT_24 = "+1); " + NL + "    \t}" + NL + "    \tif (dir";
  protected final String TEXT_25 = "!=null && !\"\".equals(dir";
  protected final String TEXT_26 = ")) ftp";
  protected final String TEXT_27 = ".chdir(dir";
  protected final String TEXT_28 = ");" + NL + "    \tmask";
  protected final String TEXT_29 = " = mask";
  protected final String TEXT_30 = ".replaceAll(\"\\\\.\", \"\\\\\\\\.\").replaceAll(\"\\\\*\", \".*\");" + NL + "\t\tString[] listings";
  protected final String TEXT_31 = " = ftp";
  protected final String TEXT_32 = ".dir(\".\", false);" + NL + "\t\tfor (int m";
  protected final String TEXT_33 = " = 0; m";
  protected final String TEXT_34 = " < listings";
  protected final String TEXT_35 = ".length; m";
  protected final String TEXT_36 = "++)" + NL + "\t\t{  " + NL + "\t\t\tif (listings";
  protected final String TEXT_37 = "[m";
  protected final String TEXT_38 = "].matches(mask";
  protected final String TEXT_39 = "))" + NL + "\t\t\t{" + NL + "\t\t\t\tftp";
  protected final String TEXT_40 = ".delete(listings";
  protected final String TEXT_41 = "[m";
  protected final String TEXT_42 = "]);" + NL + "\t\t\t}" + NL + "\t\t}\t     " + NL + "   \t}  " + NL + "   ftp";
  protected final String TEXT_43 = ".chdir(root";
  protected final String TEXT_44 = ");   " + NL + " } " + NL;
  protected final String TEXT_45 = NL;

  public String generate(Object argument)
  {
    final StringBuffer stringBuffer = new StringBuffer();
    stringBuffer.append(TEXT_1);
    
	CodeGeneratorArgument codeGenArgument = (CodeGeneratorArgument) argument;
	INode node = (INode)codeGenArgument.getArgument();
	String cid = node.getUniqueName();

    stringBuffer.append(TEXT_2);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_3);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_4);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_5);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_6);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_7);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_8);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_9);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_10);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_11);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_12);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_13);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_14);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_15);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_16);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_17);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_18);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_19);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_20);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_21);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_22);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_23);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_24);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_25);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_26);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_27);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_28);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_29);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_30);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_31);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_32);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_33);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_34);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_35);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_36);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_37);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_38);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_39);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_40);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_41);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_42);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_43);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_44);
    stringBuffer.append(TEXT_45);
    return stringBuffer.toString();
  }
}
