package org.talend.designer.codegen.translators.internet.ftp;

import org.talend.core.model.process.INode;
import org.talend.core.model.metadata.IMetadataTable;
import org.talend.core.model.process.ElementParameterParser;
import org.talend.designer.codegen.config.CodeGeneratorArgument;
import java.util.List;
import java.util.Map;

public class TFTPPutMainJava
{
  protected static String nl;
  public static synchronized TFTPPutMainJava create(String lineSeparator)
  {
    nl = lineSeparator;
    TFTPPutMainJava result = new TFTPPutMainJava();
    nl = null;
    return result;
  }

  public final String NL = nl == null ? (System.getProperties().getProperty("line.separator")) : nl;
  protected final String TEXT_1 = "";
  protected final String TEXT_2 = "\t";
  protected final String TEXT_3 = "\t" + NL + "\tftp";
  protected final String TEXT_4 = ".setType(com.enterprisedt.net.ftp.FTPTransferType.BINARY);";
  protected final String TEXT_5 = "\t" + NL + "\tftp";
  protected final String TEXT_6 = ".setType(com.enterprisedt.net.ftp.FTPTransferType.ASCII);";
  protected final String TEXT_7 = NL + "\tString localdir";
  protected final String TEXT_8 = "  = ";
  protected final String TEXT_9 = ";\t" + NL + "\tfor (java.util.Map<String, String> map";
  protected final String TEXT_10 = " : list";
  protected final String TEXT_11 = ") " + NL + "\t{" + NL + "   \t\tjava.util.Set<String> keySet";
  protected final String TEXT_12 = " = map";
  protected final String TEXT_13 = ".keySet();" + NL + "      \tfor (String key";
  protected final String TEXT_14 = " : keySet";
  protected final String TEXT_15 = ")" + NL + "   \t\t{     " + NL + "\t\t\tString tempdir";
  protected final String TEXT_16 = " =  localdir";
  protected final String TEXT_17 = ";" + NL + "\t\t\tString filemask";
  protected final String TEXT_18 = " = key";
  protected final String TEXT_19 = "; " + NL + "\t\t\tString dir";
  protected final String TEXT_20 = " = null;\t" + NL + "\t\t\tString mask";
  protected final String TEXT_21 = " = filemask";
  protected final String TEXT_22 = ".replaceAll(\"\\\\\\\\\", \"/\") ;\t" + NL + "\t\t\tint i";
  protected final String TEXT_23 = " = mask";
  protected final String TEXT_24 = ".lastIndexOf('/');" + NL + "  \t\t\tif (i";
  protected final String TEXT_25 = "!=-1)" + NL + "\t\t\t{" + NL + "\t\t\t\tdir";
  protected final String TEXT_26 = " = mask";
  protected final String TEXT_27 = ".substring(0, i";
  protected final String TEXT_28 = "); " + NL + "\t\t\t\tmask";
  protected final String TEXT_29 = " = mask";
  protected final String TEXT_30 = ".substring(i";
  protected final String TEXT_31 = "+1);\t " + NL + "    \t\t}" + NL + "    \t\tif (dir";
  protected final String TEXT_32 = "!=null && !\"\".equals(dir";
  protected final String TEXT_33 = ")) tempdir";
  protected final String TEXT_34 = " = tempdir";
  protected final String TEXT_35 = " + \"/\" + dir";
  protected final String TEXT_36 = ";  " + NL + "    \t\tmask";
  protected final String TEXT_37 = " = mask";
  protected final String TEXT_38 = ".replaceAll(\"\\\\.\", \"\\\\\\\\.\").replaceAll(\"\\\\*\", \".*\");" + NL + "    \t\tfinal String finalMask";
  protected final String TEXT_39 = " = mask";
  protected final String TEXT_40 = ";" + NL + "    \t\tjava.io.File[] listings";
  protected final String TEXT_41 = " = null;       " + NL + "        \tjava.io.File file";
  protected final String TEXT_42 = " = new java.io.File(tempdir";
  protected final String TEXT_43 = ");" + NL + "        \tif (file";
  protected final String TEXT_44 = ".isDirectory()) {" + NL + "            listings";
  protected final String TEXT_45 = " = file";
  protected final String TEXT_46 = ".listFiles(new java.io.FileFilter() {" + NL + "                public boolean accept(java.io.File pathname) {" + NL + "                    boolean result = false;" + NL + "                    if (pathname != null && pathname.isFile()) {                      " + NL + "                            result = java.util.regex.Pattern.compile(finalMask";
  protected final String TEXT_47 = ").matcher(pathname.getName()).find(); " + NL + "                    \t}" + NL + "                    return result;" + NL + "                \t}" + NL + "            \t});" + NL + "        \t} " + NL + "    \tif(listings";
  protected final String TEXT_48 = " != null)" + NL + "    \t{" + NL + "    \t\tfor (int m";
  protected final String TEXT_49 = " = 0; m";
  protected final String TEXT_50 = " < listings";
  protected final String TEXT_51 = ".length; m";
  protected final String TEXT_52 = "++)" + NL + "     \t\t{ " + NL + "      \t\t\tif (listings";
  protected final String TEXT_53 = "[m";
  protected final String TEXT_54 = "].getName().matches(mask";
  protected final String TEXT_55 = "))" + NL + "      \t\t\t\t{        " + NL + "        \t\t\t\t ";
  protected final String TEXT_56 = NL + "            \t\t\t\tif(!(ftp";
  protected final String TEXT_57 = ".exists(listings";
  protected final String TEXT_58 = "[m";
  protected final String TEXT_59 = "].getName())))" + NL + "            \t\t\t\t{" + NL + "            \t\t\t\t\tftp";
  protected final String TEXT_60 = ".put(tempdir";
  protected final String TEXT_61 = " + \"/\" + listings";
  protected final String TEXT_62 = "[m";
  protected final String TEXT_63 = "].getName(),listings";
  protected final String TEXT_64 = "[m";
  protected final String TEXT_65 = "].getName());" + NL + "            \t\t\t\t}" + NL + "            \t\t\t";
  protected final String TEXT_66 = NL + "            \t\t\t";
  protected final String TEXT_67 = NL + "            \t\t\t\t ftp";
  protected final String TEXT_68 = ".put(tempdir";
  protected final String TEXT_69 = " + \"/\" + listings";
  protected final String TEXT_70 = "[m";
  protected final String TEXT_71 = "].getName(),listings";
  protected final String TEXT_72 = "[m";
  protected final String TEXT_73 = "].getName());" + NL + "            \t\t\t";
  protected final String TEXT_74 = NL + "            \t\t\t";
  protected final String TEXT_75 = NL + "            \t\t\t\tif((ftp";
  protected final String TEXT_76 = ".exists(listings";
  protected final String TEXT_77 = "[m";
  protected final String TEXT_78 = "].getName())))" + NL + "            \t\t\t\t{" + NL + "            \t\t\t\t\tcom.enterprisedt.net.ftp.FTPFile ftpfile";
  protected final String TEXT_79 = "=ftp";
  protected final String TEXT_80 = ".fileDetails(listings";
  protected final String TEXT_81 = "[m";
  protected final String TEXT_82 = "].getName());" + NL + "        \t\t\t\t\t\tlong ftpSize";
  protected final String TEXT_83 = "=ftpfile";
  protected final String TEXT_84 = ".size();" + NL + "        \t\t\t\t\t\tlong localSize";
  protected final String TEXT_85 = "=listings";
  protected final String TEXT_86 = "[m";
  protected final String TEXT_87 = "].length();" + NL + "        \t\t\t\t\t\tif(!(ftpSize";
  protected final String TEXT_88 = "==localSize";
  protected final String TEXT_89 = "))" + NL + "        \t\t\t\t\t\t{" + NL + "            \t\t\t\t\t\tftp";
  protected final String TEXT_90 = ".put(tempdir";
  protected final String TEXT_91 = " + \"/\" + listings";
  protected final String TEXT_92 = "[m";
  protected final String TEXT_93 = "].getName(),listings";
  protected final String TEXT_94 = "[m";
  protected final String TEXT_95 = "].getName());" + NL + "            \t\t\t\t\t}" + NL + "            \t\t\t\t}else" + NL + "            \t\t\t\t{" + NL + "            \t\t\t\t\tftp";
  protected final String TEXT_96 = ".put(tempdir";
  protected final String TEXT_97 = " + \"/\" + listings";
  protected final String TEXT_98 = "[m";
  protected final String TEXT_99 = "].getName(),listings";
  protected final String TEXT_100 = "[m";
  protected final String TEXT_101 = "].getName());" + NL + "            \t\t\t\t}" + NL + "            \t\t\t";
  protected final String TEXT_102 = NL + "      \t\t\t\t}" + NL + "    \t\t}" + NL + "    \t}     " + NL + "    }" + NL + " }";

  public String generate(Object argument)
  {
    final StringBuffer stringBuffer = new StringBuffer();
    stringBuffer.append(TEXT_1);
    
	CodeGeneratorArgument codeGenArgument = (CodeGeneratorArgument) argument;
	INode node = (INode)codeGenArgument.getArgument();
	String localdir = ElementParameterParser.getValue(node, "__LOCALDIR__");	
	String cid = node.getUniqueName();
	String overwrite=ElementParameterParser.getValue(node, "__OVERWRITE__");

    stringBuffer.append(TEXT_2);
     
	if ("binary".equalsIgnoreCase(ElementParameterParser.getValue(node, "__MODE__"))) {

    stringBuffer.append(TEXT_3);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_4);
    
  }	else {  

    stringBuffer.append(TEXT_5);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_6);
    
 }

    stringBuffer.append(TEXT_7);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_8);
    stringBuffer.append(localdir);
    stringBuffer.append(TEXT_9);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_10);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_11);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_12);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_13);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_14);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_15);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_16);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_17);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_18);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_19);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_20);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_21);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_22);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_23);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_24);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_25);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_26);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_27);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_28);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_29);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_30);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_31);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_32);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_33);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_34);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_35);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_36);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_37);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_38);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_39);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_40);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_41);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_42);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_43);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_44);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_45);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_46);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_47);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_48);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_49);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_50);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_51);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_52);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_53);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_54);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_55);
    if(overwrite.equals("never")){
    stringBuffer.append(TEXT_56);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_57);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_58);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_59);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_60);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_61);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_62);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_63);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_64);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_65);
    }
    stringBuffer.append(TEXT_66);
    if(overwrite.equals("always")){
    stringBuffer.append(TEXT_67);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_68);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_69);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_70);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_71);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_72);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_73);
    }
    stringBuffer.append(TEXT_74);
     if(overwrite.equals("size_differ")){
    stringBuffer.append(TEXT_75);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_76);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_77);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_78);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_79);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_80);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_81);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_82);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_83);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_84);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_85);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_86);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_87);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_88);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_89);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_90);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_91);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_92);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_93);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_94);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_95);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_96);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_97);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_98);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_99);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_100);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_101);
    }
    stringBuffer.append(TEXT_102);
    return stringBuffer.toString();
  }
}
